# Parameters for the Pioneer P3-DX robot

lookahead_distance: 0.02
max_linear_velocity: 0.1
max_rotational_velocity: 2.0
position_tolerance: 0.05
map_frame_id: odom
# map_frame_id: robot_1/odom
robot_frame_id: base_link
lookahead_frame_id: lookahead

